import { describe, expect, it } from "vitest";
import { money } from "../server/domain/money";
import { calculateCustomerProfitability } from "../server/engines/customer";
import { calculateCampaignEconomics } from "../server/engines/marketing";
import { calculateCashFlow } from "../server/engines/cashFlow";

const scope = { organizationId: "org", storeId: "store", mode: "demo" as const }; const customer = { ...scope, id: "customer", source: "demo" as const, status: "actual" as const };
const order = (id: string, at: string) => ({ ...scope, id, customerId: customer.id, source: "demo" as const, status: "paid" as const, currency: "SAR", merchandiseGross: money(10000), discounts: money(1000), shippingCharged: money(0), refundedAmount: money(0), revenueBasis: "tax_inclusive" as const, orderedAt: at });
const result = (profit = money(3000)) => ({ status: "actual" as const, trueCost: money(6000), trueProfit: profit });
describe("customer, marketing, and cash-flow foundations", () => {
  it("aggregates scoped historical customer profitability without inventing LTV", () => { const orders = [order("a", "2026-08-01"), order("b", "2026-09-01")]; const value = calculateCustomerProfitability({ customer, orders, trueCosts: new Map(orders.map((x) => [x.id, result()] as const)), calculatedAt: "2026-09-20", rules: { referenceDate: "2026-09-20", highProfitTrueProfit: money(5000) } }); expect(value.orderCount).toBe(2); expect(value.historicalRevenue).toBe(18000); expect(value.trueProfit).toBe(6000); expect(value.segments).toContain("returning"); expect(value.estimatedLtv).toBeUndefined(); });
  it("propagates incomplete order profitability rather than calling revenue customer value", () => { const value = calculateCustomerProfitability({ customer, orders: [order("a", "2026-09-01")], trueCosts: new Map(), calculatedAt: "2026-09-20", rules: { referenceDate: "2026-09-20" } }); expect(value.status).toBe("incomplete"); expect(value.trueProfit).toBeUndefined(); });
  it("calculates campaign ROAS/CAC without double-subtracting included advertising", () => { const o = order("a", "2026-09-01"); const campaign = { ...scope, id: "campaign", channel: "Meta", name: "Demo", currency: "SAR", spend: money(2000), dateFrom: "2026-09-01", dateTo: "2026-09-30", source: "demo" as const, status: "estimated" as const, attributionModel: "last_click" as const }; const value = calculateCampaignEconomics({ campaign, attributions: [{ ...scope, id: "attr", campaignId: campaign.id, orderId: o.id, customerId: customer.id, source: "demo", status: "estimated", attributionModel: "last_click", attributedAt: o.orderedAt }], orders: [o], trueCosts: new Map([[o.id, result()]]), advertisingCostTreatment: "included_in_true_cost", calculatedAt: "2026-09-20" }); expect(value.roas).toBe(4.5); expect(value.cac).toBe(2000); expect(value.profitAfterAdvertising).toBe(3000); });
  it("omits campaign ratios for zero spend or zero acquired customers", () => { const campaign = { ...scope, id: "campaign", channel: "Meta", name: "Demo", currency: "SAR", spend: money(0), dateFrom: "2026-09-01", dateTo: "2026-09-30", source: "demo" as const, status: "actual" as const, attributionModel: "last_click" as const }; const value = calculateCampaignEconomics({ campaign, attributions: [], orders: [], trueCosts: new Map(), advertisingCostTreatment: "not_included_in_true_cost", calculatedAt: "2026-09-20" }); expect(value.roas).toBeUndefined(); expect(value.cac).toBeUndefined(); });
  it("keeps cash balance, flow, obligations, and currency completeness distinct", () => { const value = calculateCashFlow({ scope, currency: "SAR", openingCash: money(10000), knownObligations: money(2000), obligationsKnown: true, horizonStart: "2026-09-01", horizonEnd: "2026-09-30", calculatedAt: "2026-09-20", entries: [{ ...scope, id: "in", direction: "inflow", category: "sale", amount: money(3000), currency: "SAR", occurredAt: "2026-09-10", expected: false, source: "demo", status: "actual" }, { ...scope, id: "out", direction: "outflow", category: "refund", amount: money(13000), currency: "SAR", occurredAt: "2026-09-11", expected: true, source: "demo", status: "estimated" }] }); expect(value.projectedCash).toBe(-2000); expect(value.obligationsStatus).toBe("provided"); expect(value.status).toBe("estimated"); });
});
