import { describe, expect, it } from "vitest";
import { orderItems } from "../server/db/schema";
import { PostgresCommerceRepository, safeNumber } from "../server/repositories/postgresCommerce";
describe("PostgreSQL Order Item persistence contract",()=>{
 it("defines scoped provider identity and scoped parent columns",()=>{for(const column of [orderItems.organizationId,orderItems.storeId,orderItems.platform,orderItems.externalId,orderItems.orderId,orderItems.productId,orderItems.variantId])expect(column).toBeDefined();expect(orderItems.productId.notNull).toBe(false);expect(orderItems.variantId.notNull).toBe(false);});
 it("preserves quantity and explicit zero money safely",()=>{expect(orderItems.quantity.name).toBe("quantity");expect(orderItems.returnedQuantity.name).toBe("returned_quantity");expect(safeNumber(0n)).toBe(0);expect(()=>safeNumber(9007199254740992n)).toThrow("safe integer");});
 it("keeps provider and ingestion timestamps distinct",()=>{expect(orderItems.sourceUpdatedAt.name).toBe("source_updated_at");expect(orderItems.ingestedAt.name).toBe("ingested_at");});
 it("hydrates scoped order item collections and preserves parent links and empty results",async()=>{const rows=[{id:"item-1",organizationId:"org-1",storeId:"store-1",platform:"salla",externalId:"external-1",source:"platform",sourceUpdatedAt:null,ingestedAt:new Date("2026-01-02T00:00:00Z"),orderId:"order-1",productId:"product-1",variantId:null,title:"Product",quantity:2,returnedQuantity:0,unitGross:5000n,discountAmount:0n}];const db={select:()=>({from:()=>({where:async()=>rows})})};const repository=new PostgresCommerceRepository(db as never);await expect(repository.listOrderItems({organizationId:"org-1",storeId:"store-1",mode:"live"},"salla")).resolves.toEqual([{id:"item-1",organizationId:"org-1",storeId:"store-1",mode:"live",externalId:"external-1",source:"platform",orderId:"order-1",productId:"product-1",variantId:undefined,title:"Product",quantity:2,returnedQuantity:0,unitGross:5000,discountAmount:0,sourceUpdatedAt:undefined}]);const emptyRepository=new PostgresCommerceRepository({select:()=>({from:()=>({where:async()=>[]})})} as never);await expect(emptyRepository.listOrderItems({organizationId:"org-1",storeId:"store-1",mode:"live"},"salla")).resolves.toEqual([]);const read=PostgresCommerceRepository.prototype.listOrderItems.toString();for(const filter of ["eq(orderItems.organizationId,scope.organizationId)","eq(orderItems.storeId,scope.storeId!)","eq(orderItems.platform,platform)"])expect(read).toContain(filter);});
});
