import { describe, expect, it } from "vitest";
import { getTableConfig } from "drizzle-orm/pg-core";
import { costAllocations, costRules, orders } from "../server/db/schema";
import { PostgresCommerceRepository } from "../server/repositories/postgresCommerce";

const hasScopedReference=(columns:readonly unknown[],foreignColumns:readonly unknown[])=>getTableConfig(costAllocations).foreignKeys.some(key=>{const reference=key.reference();return reference.columns.length===columns.length&&reference.columns.every((column,index)=>column===columns[index])&&reference.foreignColumns.every((column,index)=>column===foreignColumns[index]);});

describe("PostgreSQL Cost Allocation scope contract",()=>{
 it("requires a same-organization/store Cost Rule parent",()=>expect(hasScopedReference([costAllocations.organizationId,costAllocations.storeId,costAllocations.costRuleId],[costRules.organizationId,costRules.storeId,costRules.id])).toBe(true));
 it("requires a same-organization/store Order parent",()=>expect(hasScopedReference([costAllocations.organizationId,costAllocations.storeId,costAllocations.orderId],[orders.organizationId,orders.storeId,orders.id])).toBe(true));
 it("keeps the established required parent references and nullable allocation period",()=>{expect(costAllocations.costRuleId.notNull).toBe(true);expect(costAllocations.orderId.notNull).toBe(true);expect(costAllocations.periodFrom.notNull).toBe(false);expect(costAllocations.periodTo.notNull).toBe(false);});
 it("hydrates scoped order allocations without platform filtering and preserves empty results",async()=>{const rows=[{id:"allocation-1",organizationId:"org-1",storeId:"store-1",costRuleId:"rule-1",orderId:"order-1",amount:500n,strategy:"revenue_share",periodFrom:new Date("2026-01-01T00:00:00Z"),periodTo:new Date("2026-01-31T00:00:00Z"),source:"calculated",status:"estimated"},{id:"allocation-2",organizationId:"org-1",storeId:"store-1",costRuleId:"rule-2",orderId:"order-1",amount:0n,strategy:"manual",periodFrom:null,periodTo:null,source:"manual",status:"actual"}];const repository=new PostgresCommerceRepository({select:()=>({from:()=>({where:async()=>rows})})} as never);await expect(repository.listOrderAllocations({organizationId:"org-1",storeId:"store-1",mode:"live"},"order-1")).resolves.toEqual([{id:"allocation-1",organizationId:"org-1",storeId:"store-1",mode:"live",costRuleId:"rule-1",orderId:"order-1",amount:500,strategy:"revenue_share",allocationPeriod:{from:"2026-01-01T00:00:00.000Z",to:"2026-01-31T00:00:00.000Z"},source:"calculated",status:"estimated"},{id:"allocation-2",organizationId:"org-1",storeId:"store-1",mode:"live",costRuleId:"rule-2",orderId:"order-1",amount:0,strategy:"manual",allocationPeriod:undefined,source:"manual",status:"actual"}]);const emptyRepository=new PostgresCommerceRepository({select:()=>({from:()=>({where:async()=>[]})})} as never);await expect(emptyRepository.listOrderAllocations({organizationId:"org-1",storeId:"store-1",mode:"live"},"order-1")).resolves.toEqual([]);const read=PostgresCommerceRepository.prototype.listOrderAllocations.toString();for(const filter of ["eq(costAllocations.organizationId,scope.organizationId)","eq(costAllocations.storeId,scope.storeId!)","eq(costAllocations.orderId,orderId)"])expect(read).toContain(filter);expect(read).not.toContain("costAllocations.platform");});
});
