import { describe, expect, it } from "vitest";
import { orders } from "../server/db/schema";
import { PostgresCommerceRepository, safeNumber } from "../server/repositories/postgresCommerce";
describe("PostgreSQL Order persistence contract",()=>{
 it("defines scoped provider identity and optional customer relationship",()=>{for(const column of [orders.organizationId,orders.storeId,orders.platform,orders.externalId,orders.customerId])expect(column).toBeDefined();expect(orders.customerId.notNull).toBe(false);});
 it("preserves explicit money zero and rejects unsafe bigint hydration",()=>{expect(safeNumber(0n)).toBe(0);expect(()=>safeNumber(9007199254740992n)).toThrow("safe integer");});
 it("persists optional tax as nullable bigint without conflating it with zero",()=>{expect(orders.taxAmount.name).toBe("tax_minor");expect(orders.taxAmount.notNull).toBe(false);expect(safeNumber(undefined)).toBeUndefined();expect(safeNumber(0n)).toBe(0);expect(safeNumber(125n)).toBe(125);expect(()=>safeNumber(9007199254740992n)).toThrow("safe integer");});
 it("keeps source and ingestion timestamps distinct",()=>{expect(orders.sourceUpdatedAt.name).toBe("source_updated_at");expect(orders.ingestedAt.name).toBe("ingested_at");expect(orders.merchandiseGross.name).toBe("merchandise_gross_minor");});
 it("hydrates scoped order collections with safe minor-unit money and preserves empty results",async()=>{const rows=[{id:"order-1",organizationId:"org-1",storeId:"store-1",platform:"salla",externalId:"external-1",source:"platform",sourceUpdatedAt:null,ingestedAt:new Date("2026-01-02T00:00:00Z"),customerId:null,status:"paid",currency:"SAR",merchandiseGross:10000n,discounts:0n,taxAmount:0n,shippingCharged:500n,refundedAmount:0n,revenueBasis:"tax_inclusive",orderedAt:new Date("2026-01-01T00:00:00Z")}];const db={select:()=>({from:()=>({where:async()=>rows})})};const repository=new PostgresCommerceRepository(db as never);await expect(repository.listOrders({organizationId:"org-1",storeId:"store-1",mode:"live"},"salla")).resolves.toEqual([{id:"order-1",organizationId:"org-1",storeId:"store-1",mode:"live",externalId:"external-1",customerId:undefined,source:"platform",status:"paid",currency:"SAR",merchandiseGross:10000,discounts:0,taxAmount:0,shippingCharged:500,refundedAmount:0,revenueBasis:"tax_inclusive",orderedAt:"2026-01-01T00:00:00.000Z",sourceUpdatedAt:undefined}]);const emptyRepository=new PostgresCommerceRepository({select:()=>({from:()=>({where:async()=>[]})})} as never);await expect(emptyRepository.listOrders({organizationId:"org-1",storeId:"store-1",mode:"live"},"salla")).resolves.toEqual([]);const read=PostgresCommerceRepository.prototype.listOrders.toString();for(const filter of ["eq(orders.organizationId,scope.organizationId)","eq(orders.storeId,scope.storeId!)","eq(orders.platform,platform)"])expect(read).toContain(filter);});
});
