-- Phase 1 core tenant foundation only; business-domain tables are deferred.
CREATE TABLE users (id CHAR(36) PRIMARY KEY, external_subject VARCHAR(191) NOT NULL UNIQUE, email VARCHAR(320), created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE organizations (id CHAR(36) PRIMARY KEY, name VARCHAR(160) NOT NULL, default_currency VARCHAR(8) NOT NULL DEFAULT 'SAR', data_mode ENUM('demo','live') NOT NULL DEFAULT 'demo', created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE organization_memberships (organization_id CHAR(36) NOT NULL, user_id CHAR(36) NOT NULL, role ENUM('owner','admin','manager','marketing','finance','inventory','viewer') NOT NULL DEFAULT 'viewer', created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, PRIMARY KEY(organization_id,user_id), INDEX organization_memberships_user_idx(user_id));
CREATE TABLE stores (id CHAR(36) PRIMARY KEY, organization_id CHAR(36) NOT NULL, name VARCHAR(160) NOT NULL, platform ENUM('salla','zid','shopify','other') NOT NULL, external_store_id VARCHAR(191), currency VARCHAR(8) NOT NULL DEFAULT 'SAR', status ENUM('active','disconnected','error','demo') NOT NULL DEFAULT 'demo', created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, INDEX stores_organization_idx(organization_id));
CREATE TABLE platform_connections (id CHAR(36) PRIMARY KEY, organization_id CHAR(36) NOT NULL, store_id CHAR(36), provider ENUM('salla','zid','shopify','other') NOT NULL, status ENUM('not_connected','requires_setup','connected','demo','error') NOT NULL DEFAULT 'requires_setup', credential_reference VARCHAR(191), last_sync_at TIMESTAMP NULL, created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, INDEX platform_connections_scope_idx(organization_id,provider));
CREATE TABLE sync_jobs (id CHAR(36) PRIMARY KEY, organization_id CHAR(36) NOT NULL, connection_id CHAR(36) NOT NULL, idempotency_key VARCHAR(191) NOT NULL, status ENUM('queued','running','succeeded','failed') NOT NULL DEFAULT 'queued', attempt INT NOT NULL DEFAULT 0, created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, UNIQUE KEY sync_jobs_idempotency_unique(organization_id,idempotency_key));
CREATE TABLE webhook_events (id CHAR(36) PRIMARY KEY, organization_id CHAR(36), provider ENUM('salla','zid','shopify','other') NOT NULL, external_event_id VARCHAR(191) NOT NULL, status ENUM('received','verified','processed','failed') NOT NULL DEFAULT 'received', received_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, UNIQUE KEY webhook_events_provider_external_unique(provider,external_event_id));
CREATE TABLE audit_events (id CHAR(36) PRIMARY KEY, organization_id CHAR(36) NOT NULL, actor_user_id CHAR(36), action VARCHAR(160) NOT NULL, entity_type VARCHAR(96) NOT NULL, entity_id CHAR(36), result ENUM('success','failure','pending') NOT NULL DEFAULT 'success', created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, INDEX audit_events_organization_idx(organization_id,created_at));
