-- Phase 1 additive security and integration foundation. It never runs automatically at application startup.
--> statement-breakpoint
ALTER TABLE "platform_connections" ADD COLUMN IF NOT EXISTS "authorization_state" text NOT NULL DEFAULT 'not_started';
ALTER TABLE "platform_connections" ADD COLUMN IF NOT EXISTS "external_account_id" text;
ALTER TABLE "platform_connections" ADD COLUMN IF NOT EXISTS "granted_scopes" jsonb NOT NULL DEFAULT '[]'::jsonb;
ALTER TABLE "platform_connections" ADD COLUMN IF NOT EXISTS "token_expires_at" timestamptz;
ALTER TABLE "products" ADD COLUMN IF NOT EXISTS "source_status" text;
ALTER TABLE "products" ALTER COLUMN "created_at" DROP NOT NULL;
ALTER TABLE "variants" ADD COLUMN IF NOT EXISTS "source_status" text;
ALTER TABLE "variants" ALTER COLUMN "name" DROP NOT NULL;
ALTER TABLE "variants" ALTER COLUMN "created_at" DROP NOT NULL;
ALTER TABLE "commerce_orders" ADD COLUMN IF NOT EXISTS "source_status" text;
ALTER TABLE "stores" ADD COLUMN IF NOT EXISTS "external_store_id" text;
CREATE UNIQUE INDEX IF NOT EXISTS "stores_provider_external_id" ON "stores" ("platform","external_store_id");
CREATE UNIQUE INDEX IF NOT EXISTS "connections_store_provider" ON "platform_connections" ("organization_id","store_id","provider");
ALTER TABLE "sync_jobs" ADD COLUMN IF NOT EXISTS "store_id" uuid NOT NULL;
ALTER TABLE "sync_jobs" ADD COLUMN IF NOT EXISTS "webhook_event_id" uuid;
ALTER TABLE "sync_jobs" ADD COLUMN IF NOT EXISTS "data_mode" text NOT NULL DEFAULT 'live';
ALTER TABLE "sync_jobs" ADD COLUMN IF NOT EXISTS "provider" text NOT NULL DEFAULT 'salla';
ALTER TABLE "sync_jobs" ADD COLUMN IF NOT EXISTS "resource" text NOT NULL DEFAULT 'initial';
ALTER TABLE "sync_jobs" ADD COLUMN IF NOT EXISTS "run_after" timestamptz NOT NULL DEFAULT now();
ALTER TABLE "sync_jobs" ADD COLUMN IF NOT EXISTS "lease_expires_at" timestamptz;
ALTER TABLE "sync_jobs" ADD COLUMN IF NOT EXISTS "completed_at" timestamptz;
ALTER TABLE "sync_jobs" ADD COLUMN IF NOT EXISTS "last_error" text;
ALTER TABLE "sync_jobs" ADD COLUMN IF NOT EXISTS "created_at" timestamptz NOT NULL DEFAULT now();
ALTER TABLE "sync_jobs" ADD COLUMN IF NOT EXISTS "updated_at" timestamptz NOT NULL DEFAULT now();
ALTER TABLE "webhook_events" ADD COLUMN IF NOT EXISTS "store_id" uuid NOT NULL;
ALTER TABLE "webhook_events" ADD COLUMN IF NOT EXISTS "connection_id" uuid;
ALTER TABLE "webhook_events" ADD COLUMN IF NOT EXISTS "data_mode" text NOT NULL DEFAULT 'live';
ALTER TABLE "webhook_events" ADD COLUMN IF NOT EXISTS "event_type" text;
ALTER TABLE "webhook_events" ADD COLUMN IF NOT EXISTS "payload_hash" text;
ALTER TABLE "webhook_events" ADD COLUMN IF NOT EXISTS "attempt" integer NOT NULL DEFAULT 0;
ALTER TABLE "webhook_events" ADD COLUMN IF NOT EXISTS "processed_at" timestamptz;
ALTER TABLE "webhook_events" ADD COLUMN IF NOT EXISTS "failed_at" timestamptz;
ALTER TABLE "webhook_events" ADD COLUMN IF NOT EXISTS "last_error" text;
ALTER TABLE "sync_jobs" ALTER COLUMN "store_id" SET NOT NULL;
ALTER TABLE "webhook_events" ALTER COLUMN "organization_id" SET NOT NULL;
ALTER TABLE "webhook_events" ALTER COLUMN "store_id" SET NOT NULL;
ALTER TABLE "audit_events" ADD COLUMN IF NOT EXISTS "store_id" uuid;
ALTER TABLE "audit_events" ADD COLUMN IF NOT EXISTS "request_id" text;
ALTER TABLE "audit_events" ADD COLUMN IF NOT EXISTS "metadata" jsonb;
CREATE TABLE IF NOT EXISTS "oauth_states" ("id" uuid PRIMARY KEY, "organization_id" uuid NOT NULL, "store_id" uuid NOT NULL, "provider" text NOT NULL, "data_mode" text NOT NULL DEFAULT 'live', "redirect_uri" text NOT NULL, "expires_at" timestamptz NOT NULL, "consumed_at" timestamptz, "created_at" timestamptz NOT NULL DEFAULT now());
ALTER TABLE "oauth_states" ADD COLUMN IF NOT EXISTS "data_mode" text NOT NULL DEFAULT 'live';
CREATE UNIQUE INDEX IF NOT EXISTS "oauth_state_scope" ON "oauth_states" ("organization_id","store_id","provider","id");
CREATE TABLE IF NOT EXISTS "integration_checkpoints" ("id" uuid PRIMARY KEY, "organization_id" uuid NOT NULL, "store_id" uuid NOT NULL, "connection_id" uuid NOT NULL, "resource" text NOT NULL, "cursor" text, "source_updated_at" timestamptz, "last_succeeded_at" timestamptz, "last_error" text);
CREATE UNIQUE INDEX IF NOT EXISTS "checkpoint_identity" ON "integration_checkpoints" ("organization_id","store_id","connection_id","resource");
CREATE TABLE IF NOT EXISTS "provider_credentials" ("id" uuid PRIMARY KEY, "organization_id" uuid NOT NULL, "store_id" uuid NOT NULL, "connection_id" uuid NOT NULL, "provider" text NOT NULL, "access_token_ciphertext" text NOT NULL, "refresh_token_ciphertext" text, "token_expires_at" timestamptz, "created_at" timestamptz NOT NULL DEFAULT now(), "updated_at" timestamptz NOT NULL DEFAULT now());
CREATE UNIQUE INDEX IF NOT EXISTS "credentials_connection_identity" ON "provider_credentials" ("organization_id","store_id","connection_id","provider");
--> statement-breakpoint
ALTER TABLE "provider_credentials" ADD CONSTRAINT "credentials_connection_scope_fk" FOREIGN KEY ("organization_id","store_id","connection_id") REFERENCES "platform_connections" ("organization_id","store_id","id");
ALTER TABLE "sync_jobs" ADD CONSTRAINT "sync_jobs_connection_scope_fk" FOREIGN KEY ("organization_id","store_id","connection_id") REFERENCES "platform_connections" ("organization_id","store_id","id");
ALTER TABLE "webhook_events" ADD CONSTRAINT "webhook_events_connection_scope_fk" FOREIGN KEY ("organization_id","store_id","connection_id") REFERENCES "platform_connections" ("organization_id","store_id","id");
ALTER TABLE "integration_checkpoints" ADD CONSTRAINT "checkpoints_connection_scope_fk" FOREIGN KEY ("organization_id","store_id","connection_id") REFERENCES "platform_connections" ("organization_id","store_id","id");
ALTER TABLE "webhook_events" ADD CONSTRAINT "webhook_events_scoped_id" UNIQUE ("organization_id","store_id","id");
ALTER TABLE "sync_jobs" ADD CONSTRAINT "sync_jobs_webhook_scope_fk" FOREIGN KEY ("organization_id","store_id","webhook_event_id") REFERENCES "webhook_events" ("organization_id","store_id","id");
--> statement-breakpoint
DROP INDEX IF EXISTS "webhook_identity";
CREATE UNIQUE INDEX "webhook_identity" ON "webhook_events" ("organization_id","store_id","provider","external_event_id");
DROP INDEX IF EXISTS "sync_idempotency";
CREATE UNIQUE INDEX "sync_idempotency" ON "sync_jobs" ("organization_id","store_id","idempotency_key");
--> statement-breakpoint
REVOKE ALL ON TABLE "organizations", "stores", "users", "organization_memberships", "platform_connections", "provider_credentials", "sync_jobs", "webhook_events", "audit_events", "products", "variants", "customers", "commerce_orders", "order_items", "inventory_facts", "cost_rules", "cost_allocations", "oauth_states", "integration_checkpoints" FROM anon, authenticated;
ALTER TABLE "organizations" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "stores" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "users" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "organization_memberships" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "platform_connections" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "provider_credentials" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "sync_jobs" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "webhook_events" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "audit_events" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "products" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "variants" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "customers" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "commerce_orders" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "order_items" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "inventory_facts" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "cost_rules" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "cost_allocations" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "oauth_states" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "integration_checkpoints" ENABLE ROW LEVEL SECURITY;
-- Defense in depth for any future explicitly-granted browser reads. Writes remain server-only.
CREATE POLICY "pp_user_self_read" ON "users" FOR SELECT TO authenticated USING ("external_subject" = auth.uid()::text);
CREATE POLICY "pp_membership_self_read" ON "organization_memberships" FOR SELECT TO authenticated USING (EXISTS (SELECT 1 FROM "users" u WHERE u."id" = "organization_memberships"."user_id" AND u."external_subject" = auth.uid()::text));
CREATE POLICY "pp_organization_member_read" ON "organizations" FOR SELECT TO authenticated USING (EXISTS (SELECT 1 FROM "organization_memberships" m JOIN "users" u ON u."id" = m."user_id" WHERE m."organization_id" = "organizations"."id" AND u."external_subject" = auth.uid()::text));
CREATE POLICY "pp_store_member_read" ON "stores" FOR SELECT TO authenticated USING (EXISTS (SELECT 1 FROM "organization_memberships" m JOIN "users" u ON u."id" = m."user_id" WHERE m."organization_id" = "stores"."organization_id" AND u."external_subject" = auth.uid()::text));
CREATE POLICY "pp_connection_member_read" ON "platform_connections" FOR SELECT TO authenticated USING (EXISTS (SELECT 1 FROM "organization_memberships" m JOIN "users" u ON u."id" = m."user_id" WHERE m."organization_id" = "platform_connections"."organization_id" AND u."external_subject" = auth.uid()::text));
CREATE POLICY "pp_sync_member_read" ON "sync_jobs" FOR SELECT TO authenticated USING (EXISTS (SELECT 1 FROM "organization_memberships" m JOIN "users" u ON u."id" = m."user_id" WHERE m."organization_id" = "sync_jobs"."organization_id" AND u."external_subject" = auth.uid()::text));
CREATE POLICY "pp_webhook_member_read" ON "webhook_events" FOR SELECT TO authenticated USING (EXISTS (SELECT 1 FROM "organization_memberships" m JOIN "users" u ON u."id" = m."user_id" WHERE m."organization_id" = "webhook_events"."organization_id" AND u."external_subject" = auth.uid()::text));
CREATE POLICY "pp_audit_member_read" ON "audit_events" FOR SELECT TO authenticated USING (EXISTS (SELECT 1 FROM "organization_memberships" m JOIN "users" u ON u."id" = m."user_id" WHERE m."organization_id" = "audit_events"."organization_id" AND u."external_subject" = auth.uid()::text));
CREATE POLICY "pp_products_member_read" ON "products" FOR SELECT TO authenticated USING (EXISTS (SELECT 1 FROM "organization_memberships" m JOIN "users" u ON u."id" = m."user_id" WHERE m."organization_id" = "products"."organization_id" AND u."external_subject" = auth.uid()::text));
CREATE POLICY "pp_variants_member_read" ON "variants" FOR SELECT TO authenticated USING (EXISTS (SELECT 1 FROM "organization_memberships" m JOIN "users" u ON u."id" = m."user_id" WHERE m."organization_id" = "variants"."organization_id" AND u."external_subject" = auth.uid()::text));
CREATE POLICY "pp_customers_member_read" ON "customers" FOR SELECT TO authenticated USING (EXISTS (SELECT 1 FROM "organization_memberships" m JOIN "users" u ON u."id" = m."user_id" WHERE m."organization_id" = "customers"."organization_id" AND u."external_subject" = auth.uid()::text));
CREATE POLICY "pp_orders_member_read" ON "commerce_orders" FOR SELECT TO authenticated USING (EXISTS (SELECT 1 FROM "organization_memberships" m JOIN "users" u ON u."id" = m."user_id" WHERE m."organization_id" = "commerce_orders"."organization_id" AND u."external_subject" = auth.uid()::text));
CREATE POLICY "pp_order_items_member_read" ON "order_items" FOR SELECT TO authenticated USING (EXISTS (SELECT 1 FROM "organization_memberships" m JOIN "users" u ON u."id" = m."user_id" WHERE m."organization_id" = "order_items"."organization_id" AND u."external_subject" = auth.uid()::text));
CREATE POLICY "pp_inventory_member_read" ON "inventory_facts" FOR SELECT TO authenticated USING (EXISTS (SELECT 1 FROM "organization_memberships" m JOIN "users" u ON u."id" = m."user_id" WHERE m."organization_id" = "inventory_facts"."organization_id" AND u."external_subject" = auth.uid()::text));
CREATE POLICY "pp_cost_rules_member_read" ON "cost_rules" FOR SELECT TO authenticated USING (EXISTS (SELECT 1 FROM "organization_memberships" m JOIN "users" u ON u."id" = m."user_id" WHERE m."organization_id" = "cost_rules"."organization_id" AND u."external_subject" = auth.uid()::text));
CREATE POLICY "pp_cost_allocations_member_read" ON "cost_allocations" FOR SELECT TO authenticated USING (EXISTS (SELECT 1 FROM "organization_memberships" m JOIN "users" u ON u."id" = m."user_id" WHERE m."organization_id" = "cost_allocations"."organization_id" AND u."external_subject" = auth.uid()::text));
CREATE POLICY "pp_oauth_state_member_read" ON "oauth_states" FOR SELECT TO authenticated USING (EXISTS (SELECT 1 FROM "organization_memberships" m JOIN "users" u ON u."id" = m."user_id" WHERE m."organization_id" = "oauth_states"."organization_id" AND u."external_subject" = auth.uid()::text));
CREATE POLICY "pp_checkpoint_member_read" ON "integration_checkpoints" FOR SELECT TO authenticated USING (EXISTS (SELECT 1 FROM "organization_memberships" m JOIN "users" u ON u."id" = m."user_id" WHERE m."organization_id" = "integration_checkpoints"."organization_id" AND u."external_subject" = auth.uid()::text));
