import { money } from "../../../server/domain/money";
import type { Customer } from "../../../server/domain/customer";
import type { MarketingCampaign } from "../../../server/domain/marketing";
import { calculateCustomerProfitability } from "../../../server/engines/customer";
import { calculateCampaignEconomics } from "../../../server/engines/marketing";
import { calculateCashFlow } from "../../../server/engines/cashFlow";
import { calculateTrueCost } from "../../../server/engines/trueCost";
import type { CostRule, Order, OrderItem } from "../../../server/domain/commerce";

const scope = { organizationId: "demo-profitpilot", storeId: "demo-store", mode: "demo" as const }; const sar = new Intl.NumberFormat("en-SA", { style: "currency", currency: "SAR", minimumFractionDigits: 2 });
const display = (value?: number) => value === undefined ? "Incomplete" : sar.format(value / 100);
const rules: CostRule[] = [{ ...scope, id: "product", category: "product_cost", scope: "product", targetId: "pima", name: "Pima cost", calculation: "per_unit", amount: money(4200), source: "demo", status: "estimated", effectiveFrom: "2026-01-01" }, { ...scope, id: "shipping", category: "shipping", scope: "order", name: "Shipping", calculation: "fixed", amount: money(1800), source: "demo", status: "estimated", effectiveFrom: "2026-01-01" }, { ...scope, id: "payment", category: "payment_fee", scope: "order", name: "Payment", calculation: "percentage", percentageBps: 250, fixedFee: money(100), source: "demo", status: "estimated", effectiveFrom: "2026-01-01" }];
const customer: Customer = { ...scope, id: "customer-noura", externalId: "demo-customer-1", source: "demo", displayName: "Noura A.", status: "estimated" };
const orders: Order[] = [
  { ...scope, id: "customer-order-1", customerId: customer.id, source: "demo", status: "paid", currency: "SAR", merchandiseGross: money(14900), discounts: money(0), shippingCharged: money(0), refundedAmount: money(0), revenueBasis: "tax_inclusive", orderedAt: "2026-08-10T00:00:00Z" },
  { ...scope, id: "customer-order-2", customerId: customer.id, source: "demo", status: "paid", currency: "SAR", merchandiseGross: money(14900), discounts: money(1000), shippingCharged: money(0), refundedAmount: money(0), revenueBasis: "tax_inclusive", orderedAt: "2026-09-10T00:00:00Z" },
];
const items: OrderItem[] = orders.map((order) => ({ ...scope, id: `${order.id}-item`, orderId: order.id, productId: "pima", source: "demo", title: "IRONCLAD Pima T-Shirt", quantity: 1, returnedQuantity: 0, unitGross: order.merchandiseGross, discountAmount: order.discounts }));
const trueCosts = new Map(orders.map((order) => [order.id, calculateTrueCost({ order, items: items.filter((item) => item.orderId === order.id), rules, calculatedAt: "2026-09-19T00:00:00Z" })]));
export function demoCustomerDisplay() { const value = calculateCustomerProfitability({ customer, orders, trueCosts, calculatedAt: "2026-09-19T00:00:00Z", rules: { referenceDate: "2026-09-19T00:00:00Z", highValueTrueProfit: money(10000), highProfitTrueProfit: money(8000), atRiskAfterDays: 60, highRevenueLowProfitMarginBps: 1500, discountSensitiveBps: 1000 }, customerAcquisitionCost: money(2400) }); return { name: customer.displayName ?? "Demo customer", orders: value.orderCount, revenue: display(value.historicalRevenue), trueProfit: display(value.trueProfit), aov: display(value.averageOrderValue), segments: value.segments.join(" · "), status: value.status, missing: value.missingInputs }; }
const campaign: MarketingCampaign = { ...scope, id: "campaign-pima", channel: "Meta", name: "Pima Retargeting", currency: "SAR", spend: money(4800), dateFrom: "2026-09-01", dateTo: "2026-09-19", source: "demo", status: "estimated", attributionModel: "last_click", confidenceBps: 6500 };
export function demoCampaignDisplay() { const value = calculateCampaignEconomics({ campaign, attributions: orders.map((order, index) => ({ ...scope, id: `attribution-${index}`, campaignId: campaign.id, orderId: order.id, customerId: customer.id, source: "demo", status: "estimated", attributionModel: "last_click", attributedAt: order.orderedAt })), orders, trueCosts, advertisingCostTreatment: "not_included_in_true_cost", calculatedAt: "2026-09-19T00:00:00Z" }); return { name: campaign.name, spend: display(value.spend), revenue: display(value.attributedRevenue), trueProfit: display(value.profitAfterAdvertising), roas: value.roas === undefined ? "Incomplete" : `${value.roas.toFixed(2)}x`, cac: display(value.cac), status: value.status, missing: value.missingInputs }; }
export function demoCashFlowDisplay() { const value = calculateCashFlow({ scope, currency: "SAR", openingCash: money(2500000), knownObligations: money(800000), obligationsKnown: true, horizonStart: "2026-09-19", horizonEnd: "2026-09-30T23:59:59Z", calculatedAt: "2026-09-19T00:00:00Z", entries: [{ ...scope, id: "receivable", direction: "inflow", category: "receivable", amount: money(320000), currency: "SAR", occurredAt: "2026-09-25T00:00:00Z", expected: true, source: "demo", status: "estimated" }, { ...scope, id: "ads", direction: "outflow", category: "advertising_payment", amount: money(120000), currency: "SAR", occurredAt: "2026-09-24T00:00:00Z", expected: true, source: "demo", status: "estimated" }] }); return { opening: display(value.openingCash), inflows: display(value.inflows), outflows: display(value.outflows), obligations: value.obligationsStatus === "none_known" ? "No known obligations" : display(value.knownObligations), projected: display(value.projectedCash), status: value.status, missing: value.missingInputs }; }
