import { useMemo } from "react";
import { CircleHelp, Database } from "lucide-react";
import { demoCostConfigurations, type CostDisplayStatus } from "@/application/trueCostAdapter";

const routeCategory: Record<string, string | undefined> = { "/cost-settings": "product_cost", "/shipping-costs": "shipping", "/payment-fees": "payment_fee", "/packaging-costs": "packaging", "/advertising-costs": "advertising", "/subscriptions": "subscription", "/other-costs": "other" };
const label = (value: string) => value === "not_configured" ? "Not configured" : value === "no_data" ? "No data" : value[0].toUpperCase() + value.slice(1);
const tone = (status: CostDisplayStatus) => status === "actual" ? "teal" : status === "estimated" ? "violet" : status === "no_data" ? "red" : "amber";

/** A single, route-aware progressive disclosure panel for Phase 2A cost-rule semantics. */
export function CostSemanticPanel({ path }: { path: string }) {
  const rules = useMemo(demoCostConfigurations, []); const category = routeCategory[path]; const visible = category ? rules.filter((rule) => rule.category === category) : rules;
  return <section className="panel panel-pad" style={{ marginTop: 15 }} aria-label="Cost rule details"><div className="section-head"><div><h2>Cost rule details</h2><p>Demo Mode · source, scope, effective date, and completeness remain explicit without changing the OLD controls above.</p></div><Database size={17} color="#9c90f5" /></div>{visible.map((rule) => <div className="metric-row" key={rule.id}><div><strong style={{ display: "block" }}>{rule.name}</strong><span>{rule.scope} · {rule.calculation.replace("_", " ")} · {rule.recurrence.replace("_", " ")} · effective {rule.effectiveFrom}</span></div><div style={{ display: "flex", alignItems: "center", gap: 8 }}><strong className={rule.amount.unavailable ? "warn" : ""}>{rule.amount.display}</strong><span className={`tag ${tone(rule.enabled ? rule.status : "not_configured")}`}>{rule.enabled ? label(rule.status) : "Disabled"}</span></div></div>)}<div className="panel soft panel-pad" style={{ marginTop: 14 }}><div className="metric-row"><span>Source state</span><strong>Actual · Estimated · Incomplete · Not configured · No data</strong></div><div className="metric-row"><span>Missing value policy</span><strong className="warn">Incomplete — never SAR 0.00</strong></div>{path === "/payment-fees" && <div className="metric-row"><span>Payment models</span><strong>Mada · Visa · Mastercard · Apple Pay · Tamara · Tabby · custom</strong></div>}{path === "/subscriptions" && <div className="metric-row"><span>Subscription readiness</span><strong>Name · category · frequency · renewal · source · notes</strong></div>}<div className="metric-row"><span>Calculation authority</span><strong>Phase 2A True Cost engine</strong></div></div><div className="flow-stack"><CircleHelp size={14} /><span>These are Demo Mode rules; no live store or provider is connected.</span></div></section>;
}
